name: NASA Project CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js version 20
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm run install
      - run: npm run build --prefix client
